// @generated by build.rs 2026-02-09 20:45:00.918674604 UTC. DO NOT EDIT.

pub mod greeter_v1 {
    tonic::include_proto!("greeter.v1");
    pub const DESCRIPTOR_SET: &[u8] = tonic::include_file_descriptor_set!("/greeter_v1_descriptor");
}
