// @generated by build.rs 2026-02-01 14:00:14.071920611 UTC. DO NOT EDIT.

pub mod greeter_v1 {
    tonic::include_proto!("greeter.v1");
    pub const DESCRIPTOR_SET: &[u8] = tonic::include_file_descriptor_set!("/greeter_v1_descriptor");
}
