// @generated by build.rs 2026-01-11 15:47:27.384102624 UTC. DO NOT EDIT.

pub mod greeter_v1 {
    tonic::include_proto!("greeter.v1");
    pub const DESCRIPTOR_SET: &[u8] = tonic::include_file_descriptor_set!("/greeter_v1_descriptor");
}
