[package]
name = "gateway"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# Workspaces
common = { path = "../shared/common" }

# Communication
tokio.workspace = true
serde.workspace = true

# Configuration
validator.workspace = true

[dev-dependencies]
test-helpers = { path = "../shared/test-helpers" }
tempdir.workspace = true
serial_test.workspace = true