[package]
name = "gateway"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# Workspaces
common = { path = "../shared/common" }
proto-definitions = { path = "../shared/proto-definitions" }

# Communication
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

# Config & Error
validator.workspace = true
thiserror.workspace = true

# Tracing
tracing.workspace = true
tracing-subscriber.workspace = true

# gRPC
tonic.workspace = true
prost.workspace = true

[dev-dependencies]
test-helpers = { path = "../shared/test-helpers" }
tempdir.workspace = true
serial_test.workspace = true