[package]
name = "common"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
tokio.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

figment.workspace = true
tonic.workspace = true
thiserror.workspace = true
validator.workspace = true

macros.workspace = true
tonic-reflection.workspace = true

[dev-dependencies]
# Tracing
tracing-test.workspace = true

# Testing
test_helpers.workspace = true
tempdir.workspace = true
serial_test.workspace = true
