use chrono::{DateTime, Utc};
use std::path::{Path, PathBuf};
use std::{env, fs};
use walkdir::WalkDir;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let proto_root = root.join("../../protos");
    let src_dir = root.join("src");
    static PROTOS_MOD: &str = "generated_protos.rs";

    // Tracks changes
    println!("cargo::rerun-if-changed={}", proto_root.display());

    // Recursively find all .proto files (handles v1, v2, etc.)
    let protos: Vec<PathBuf> = WalkDir::new(&proto_root)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "proto"))
        .map(|e| e.into_path())
        .collect();

    if protos.is_empty() {
        println!(
            "cargo:warning=No proto files found in {}",
            proto_root.display()
        );
        return Ok(());
    }

    // Sync-on-Build: Copy generated files to src/generated for IDE support
    let current_utc: DateTime<Utc> = Utc::now();
    let mut mod_content = format!(
        "// @generated by build.rs {}. DO NOT EDIT.\n\n",
        current_utc
    );

    for proto in &protos {
        println!("cargo:rerun-if-changed={}", proto.display());

        let package_name = get_proto_package(proto.as_path());
        validate_version_consistency(proto, &package_name, &proto_root)?;

        let safe_name = package_name.replace('.', "_");
        let descriptor_path = out_dir.join(format!("{}_descriptor.bin", safe_name));

        // Compile with a specific descriptor for this package
        tonic_prost_build::configure()
            .file_descriptor_set_path(&descriptor_path)
            .build_server(true)
            .build_client(true)
            .type_attribute(".", "#[derive(serde::Serialize, serde::Deserialize)] #[serde(rename_all = \"camelCase\")]")
            .compile_protos(&[proto], &[&proto_root])?;

        // Add to our dynamic mod.rs
        mod_content.push_str(&format!(
            "pub mod {} {{\n    tonic::include_proto!(\"{}\");\n    pub const DESCRIPTOR_SET: &[u8] = tonic::include_file_descriptor_set!(\"/{}_descriptor\");\n}}\n",
            safe_name, package_name, safe_name
        ));
    }

    // Write the dynamic mod.rs
    fs::write(src_dir.join(PROTOS_MOD), mod_content)?;

    Ok(())
}

fn get_proto_package(path: &Path) -> String {
    let content = fs::read_to_string(path).expect("Could not read proto file");
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("package ") {
            // Extracts "auth.service.v1" from "package auth.service.v1;"
            return trimmed
                .trim_start_matches("package ")
                .trim_end_matches(';')
                .trim()
                .to_string();
        }
    }
    // Fallback: use filename if no package is declared
    path.file_stem().unwrap().to_str().unwrap().to_string()
}

fn validate_version_consistency(path: &Path, package: &str, root: &Path) -> Result<(), String> {
    // 1. Extract the version from the package name (e.g., "auth.v1" -> "v1")
    let package_version = package.split('.').last().unwrap_or("");

    // 2. Extract the version from the file path relative to root (e.g., ".../auth/v1/auth.proto" -> "v1")
    let relative_path = path.strip_prefix(root).map_err(|e| e.to_string())?;
    let folder_version = relative_path
        .components()
        .rev()
        .nth(1) // Get the parent folder name
        .and_then(|c| c.as_os_str().to_str())
        .unwrap_or("");

    if !package_version.starts_with('v') || package_version != folder_version {
        // Output formatted for the terminal
        println!("cargo::error=Proto Version Mismatch Found!");
        println!("cargo::error=  File:   {}", path.display());
        println!("cargo::error=  Package: {}", package);
        println!("cargo::error=  Folder:  {}", folder_version);
        println!(
            "cargo::error=Expected folder name to match the last segment of the package name."
        );

        // Return a generic error to stop the build
        return Err("Consistency check failed. See terminal output above.".to_string());
    }
    Ok(())
}
